### Importing the NumPy library for numerical operations, creating one-dimensional (1D) and two-dimensional (2D) arrays, generating matrices of zeros and ones, creating sequences with `arange()`, and evenly spaced values with `linspace()`


In [5]:
import numpy as np  #import the numpy library and give it the alias np
a = np.array([1,2,3,4]) # create a 1D numpy array.
b = np.array([[1,2,3],[4,5,6]]) # create a 2D numpy array.
z = np.zeros((3,4)) # create a 2D array of shape 3x4 filled with zeros.
o = np.ones((2,3)) # create a 2D array of shape 2x3 filled with ones.
r = np.arange(0, 10, 2) # create a 1D array starting from 0 up to (but not includeing) 10 with a step of 2
l = np.linspace(0, 1, 5) # create a 1D array of 5 evenly spaced values between 0 and 1.

In [3]:
print(a)
print(b)
print(z)
print(o)
print(r)
print(l)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### Creating a Matrix Where Every Element Is 2 or other value

In [7]:
m = np.zeros((2,3))  # any existing matrix
m[:] = 2             # Set every element to 2 (in-place)
print(m)

[[2. 2. 2.]
 [2. 2. 2.]]


In [8]:
m[:] = 5
print(m)

[[5. 5. 5.]
 [5. 5. 5.]]


In [9]:
# Ohter good options.
m = np.full((2,3), 2)  # create a new 2x3 matrix with 2.
print(m)

[[2 2 2]
 [2 2 2]]


In [11]:
m = np.ones((2,3)) * 2     # Ones multiplied by 2
print(m)

[[2. 2. 2.]
 [2. 2. 2.]]


In [13]:
m = np.zeros((2,3)) + 2    # Zeros plus 2
print(m)

[[2. 2. 2.]
 [2. 2. 2.]]


### Checking array shape, number of dimensions, and data type using `shape`, `ndim`, and `dtype`


In [17]:
print(b.shape)  
print(b.ndim)
print(b.dtype)

(2, 3)
2
int64


### Array Indexing and Slicing in NumPy

In [18]:
x = np.array([1,2,3,4,5,6,7,8,9])

print(x[0]) # access the frist element (index 0)
print(x[-1]) # access the last element using negative indexing.

1
9


In [19]:
print(x[1])        # Access the second element (index 1)
print(x[1:4])      # Slice from index 1 to 3 (index 4 is excluded)
print(x[:3])       # Slice from the beginning up to index 2
print(x[2:])       # Slice from index 2 to the end
print(x[::2])      # Select every second element using step slicing
print(x[::3])      # Select every third element using step slicing
print(x[::-1])     # Reverse the array
print(x[-3:])      # Get the last three elements
print(x[[0,2,4]])  # Access multiple specific indices at once

2
[2 3 4]
[1 2 3]
[3 4 5 6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]
[7 8 9]
[1 3 5]


### 2D Array Indexing and Slicing in NumPy

In [20]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])  # Create a 3x3 matrix

print(m[0,1])      # Element at row 0, column 1
print(m[:,1])      # All rows, column 1
print(m[1,:])      # Row 1, all columns
print(m[0:2,1:3])  # Sub-matrix: rows 0-1 and columns 1-2

2
[2 5 8]
[4 5 6]
[[2 3]
 [5 6]]


In [21]:
print(m[2,2])        # Last element (row 2, column 2)
print(m[-1,-1])      # Last element using negative indexing
print(m[:, ::2])     # All rows, every second column
print(m[::2, :])     # Every second row, all columns
print(m[::-1])       # Reverse the rows of the matrix
print(m.T)           # Transpose of the matrix (swap rows and columns)
print(m.flatten())   # Convert 2D matrix into 1D array

9
9
[[1 3]
 [4 6]
 [7 9]]
[[1 2 3]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]


### Boolean Masking and Filtering Values in NumPy

In [22]:
v = np.array([0.2, 1.5, -0.7, 3.3, 2.2])  # Create a 1D array of float values

mask = v > 1.0     # Create a boolean mask where values greater than 1.0 are True
print(mask)        # Display the boolean mask (True/False for each element)
print(v[mask])     # Use the mask to filter and print only values greater than 1.0

[False  True False  True  True]
[1.5 3.3 2.2]


### Arithmetic Operations and Statistical Functions on NumPy Arrays

In [23]:
x = np.array([[1,2],[3,4]])  # Create a 2x2 array
y = np.array([[1,2],[3,4]])  # Create another 2x2 array

print(x + y)                 # Element-wise addition
print(x - y)                 # Element-wise subtraction
print(x * y)                 # Element-wise multiplication

print(np.sum(x))             # Sum of all elements
print(np.sum(x, axis=0))     # Column-wise sum
print(np.sum(x, axis=1))     # Row-wise sum

print(x.min())               # Minimum value in the array
print(x.max())               # Maximum value in the array

print(x.min(axis=0))         # Column-wise minimum
print(x.min(axis=1))         # Row-wise minimum

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
10
[4 6]
[3 7]
1
4
[1 2]
[1 3]


### Matrix Dot Product and Shape Checking in NumPy

In [24]:
# Matrix dot product
a = np.array([[1,2,3],
              [4,5,6]])          # 2x3 matrix

b = np.array([[7,8],
              [9,10],
              [11,12]])         # 3x2 matrix

c = a.dot(b)                   # Matrix multiplication (dot product)

print(c)                       # Resulting 2x2 matrix

print(a.shape)                 # Shape of matrix a (rows, columns)
print(b.shape)                 # Shape of matrix b
print(c.shape)                 # Shape of result matrix

[[ 58  64]
 [139 154]]
(2, 3)
(3, 2)
(2, 2)


### Broadcasting with Vector and Scalar in NumPy

In [25]:
# Broadcasting
x = np.array([1,2])   # Vector (1D array)
y = np.array(3)       # Scalar value as a NumPy array

z = x + y             # Broadcasting: scalar added to each element of the vector

print(z)              # Result: [4 5]

[4 5]


### Broadcasting a Scalar with a Vector in NumPy (Short Explanation)

A scalar wrapped as `np.array(3)` becomes a 0-dimensional NumPy array.  
When added to a vector, NumPy **broadcasts** the scalar to each element.

In [26]:
x = np.array([1, 2])   # Vector
y = np.array(3)        # Scalar as 0D NumPy array

print(y.ndim)          # 0 (no dimensions)
print(y.shape)         # ()

z = x + y              # Broadcasting happens here
print(z)               # [4 5]

0
()
[4 5]


### Using `expand_dims` to Change Shape and Enable Broadcasting

In [27]:
a = np.array((3,4,5))          # 1D array with shape (3,)

b = np.expand_dims(a, axis=1) # Convert to 2D column array, shape becomes (3,1)

print(a)                      # [3 4 5]
print(b)
# [[3]
#  [4]
#  [5]]

c = a + b                     # Broadcasting between (3,) and (3,1)
print(c)                      # Result is a 3x3 matrix due to broadcasting

[3 4 5]
[[3]
 [4]
 [5]]
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


### Reshaping an Array to Enable Broadcasting in NumPy

In [28]:
a = a.reshape(-1, 1)   # Reshape 'a' into a column vector; rows auto-calculated

print(a.shape)         # Check new shape of 'a' → (3,1)

c = a + b              # Broadcasting between two (3,1) arrays

print(c.shape)         # Shape of result → (3,1)
print(c)               # Result after element-wise addition

(3, 1)
(3, 1)
[[ 6]
 [ 8]
 [10]]


In [29]:
a = np.array([3,4,5])

a = a.reshape(1, -1)   # Convert to a row vector → shape (1,3)
print(a.shape)

b = np.expand_dims(a.flatten(), axis=1)  # Column vector → shape (3,1)

c = a + b              # Broadcasting between (1,3) and (3,1)
print(c.shape)
print(c)

(1, 3)
(3, 3)
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


### Transpose of a Matrix in NumPy

In [30]:
# Transpose
x = np.array([[1,2,3],
              [4,5,6]])     # 2x3 matrix

print(x)
print(x.shape)              # (2,3)

y = np.transpose(x, (1,0)) # Swap axes → transpose ;  o = rows and 1 = coloums

print(y)
print(y.shape)              # (3,2)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


### Reshaping Arrays in NumPy

In [31]:
# Reshaping
x = np.array([[1,2,3,4,5,6]])  # 1x6 array
print(x)
print(x.shape)                 # (1,6)

y = np.reshape(x, (2,3))       # Reshape into 2 rows and 3 columns
print(y)
print(y.shape)                 # (2,3)

z = np.reshape(x, (2,-1))      # Let NumPy decide columns automatically
print(z)
print(z.shape)                 # (2,3)


[[1 2 3 4 5 6]]
(1, 6)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)


### Joining Arrays Using Concatenation and Stacking in NumPy

In [32]:
# Joining can be done via concatenation or stacking
q = np.random.randn(2,3)        # Random 2x3 array from normal distribution

x = np.array([[1,2,3],
              [4,5,6]])        # 2x3 array

print(x)
print(x.shape)                 # (2,3)

[[1 2 3]
 [4 5 6]]
(2, 3)


### Joining Arrays Using `concatenate()` Along Different Axes

In [33]:
# Joining via concatenation
y = np.concatenate([x, x], axis=0)  # Join row-wise (vertical)
print(y)
print(y.shape)                      # (4,3)

z = np.concatenate([x, x], axis=1)  # Join column-wise (horizontal)
print(z)
print(z.shape)                      # (2,6)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
(4, 3)
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
(2, 6)


### Joining Arrays Using `stack()` in NumPy

In [34]:
# Joining via stacking
z = np.stack([x, x], axis=0)   # Stack along a new axis

print(z)
print(z.shape)                 # (2, 2, 3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


### Expanding / Adding Dimensions Using `expand_dims()` in NumPy

In [36]:
# Expanding/Adding dimensions
x = np.array([[1,2,3],
              [4,5,6]])

print(x.shape)              # (2,3)

y = np.expand_dims(x, 1)   # Add a new axis at position 1

print(y)
print(y.shape)             # (2,1,3)

(2, 3)
[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)


### Removing Extra Dimensions Using `squeeze()` in NumPy

In [37]:
# Removing dimensions
x = np.array([[[1,2,3]],
              [[4,5,6]]])

print(x)
print(x.shape)            # (2,1,3)

y = np.squeeze(x, 1)     # Remove the axis with size 1 at position 1

print(y)
print(y.shape)           # (2,3)


[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)


### Statistical Functions in NumPy (mean, variance, std, covariance)

In [38]:
# Statistical functions
X = np.random.randn(2,2)      # 2x2 random values from normal distribution

mu = X.mean(axis=0)           # Column-wise mean
var = X.var(axis=0)           # Column-wise variance
sigma = X.std(axis=0)         # Column-wise standard deviation

cov = np.cov(X, rowvar=False) # Covariance matrix (columns as variables)

print(X)
print(mu)
print(var)
print(sigma)
print(cov)

[[-0.68581639  0.26590077]
 [-0.31238021  0.65436055]]
[-0.4990983   0.46013066]
[0.03486365 0.03772525]
[0.18671809 0.19422989]
[[0.06972729 0.07253247]
 [0.07253247 0.0754505 ]]
